// Narration editoriale du rapport All(IA)nce, bilingue FR/EN.
// Texte fixe repris AU MOT PRES des rapports de reference (Rapport_AllIAnce_demo.pdf / _EN.pdf).
// Les valeurs dynamiques (scores, quotes, nuage de mots) sont injectees par le composant.
export const RC = {
  fr: {
    subtitle: "Diagnostic de reddition cognitive",
    intro: "Ce rapport est une image, à un instant t, du type de lien que votre équipe entretient avec l'IA — individuellement et collectivement. Ce n'est ni une évaluation ni un jugement, mais un miroir : prendre conscience de ce que l'on fait déjà, pour pouvoir agir et créer, en conscience, l'alliance que l'on souhaite avec l'IA.",
    kpi: { resp: 'Répondants', red: 'Reddition', res: 'Résistance', pol: 'Polarité' },
    howToReadTitle: "Comment lire les scores",
    howToRead: [
      "Reddition (sur 25) — 5 à 11 : délégation saine · 12 à 18 : point de bascule · 19 à 25 : reddition cognitive. Plus le score monte, plus on adopte l'IA sans la réexaminer.",
      "Résistance (sur 20) — 4 à 9 : ouverture · 10 à 14 : refus modéré · 15 à 20 : refus rigide. Plus le score monte, plus on tient l'IA à distance."],
    polTitle: "La polarité reddition – résistance",
    polText: "Le curseur situe l'équipe entre reddition (se laisser porter par l'IA) et résistance (la tenir à distance). Aucun des deux pôles n'est un objectif ni un défaut : ce sont deux tendances complémentaires, à intégrer selon le contexte et avec un juste dosage. L'enjeu n'est pas de choisir un camp, mais de savoir doser.",
    mapTitle: "La carte reddition – résistance",
    mapText: "Chaque point est une personne ; l'étoile, la moyenne de l'équipe. Les deux axes dessinent quatre postures — au centre, une zone de transition, relation encore en train de se stabiliser :",
    postures: {
      over: "Reddition cognitive — on suit l'IA sans la réexaminer ; le jugement se délègue sans qu'on le remarque.",
      rigid: "Refus rigide — on tient l'IA à distance, parfois au prix de sa charge de travail et de son apprentissage.",
      healthy: "Intégration saine — on l'utilise avec discernement, sans la sur-croire ni la rejeter : la zone visée.",
      erratic: "Jugement oscillant — on alterne confiance aveugle et rejet de principe ; la règle du jeu reste à poser." },
    compTitle: "Les 5 compétences humaines",
    compText: "Créativité, curiosité, collaboration, esprit critique, communication : ce sont, aujourd'hui encore, les compétences les plus typiquement humaines — celles que l'IA imite le moins bien et que la sur-dépendance érode le plus vite. Les mesurer, c'est repérer où l'humain garde (ou perd) sa valeur ajoutée. Ligne dorée : la compétence que l'on se reconnaît. Ligne cuivre : à quel point on juge l'IA supérieure à soi.",
    compP21: "Ces cinq compétences forment le cœur des « compétences du XXIe siècle » (cadre P21). En bref :",
    compRefs: [
      "Créativité — produire des idées à la fois nouvelles et utiles — ce que l'IA recombine mais n'initie pas vraiment. (Amabile, 1996)",
      "Curiosité — le désir d'explorer et de creuser au-delà du strict nécessaire — moteur de l'apprentissage. (Kashdan & Silvia, 2009)",
      "Collaboration — mobiliser l'intelligence collective du groupe, supérieure à la somme des individus. (Woolley et al., Science, 2010)",
      "Esprit critique — évaluer une affirmation, ses sources et ses biais avant d'y adhérer. (Facione, rapport Delphi de l'APA, 1990)",
      "Communication — adapter son message pour être réellement compris par des interlocuteurs différents. (Hymes, 1972)"],
    compLegend: { cap: 'Compétence (vous)', sig: 'IA perçue supérieure' },
    hsdTitle: "Dynamique de l'équipe face à l'IA",
    hsdText: "Une équipe est un système. Trois conditions déterminent sa capacité à métaboliser l'arrivée de l'IA plutôt que de la subir. Un système qui régule mal l'une des trois bascule plus vite dans la reddition partagée.",
    hsdDefs: [
      "Contenant — le cadre, les rôles, les règles du jeu : qui décide quoi au sujet de l'IA.",
      "Différence — la place laissée au désaccord, à la divergence, à l'éthique : oser challenger l'IA.",
      "Échange — la circulation de l'information, le débrief, l'apprentissage collectif des erreurs."],
    atrTitle: "Écart d'atrophie moyen",
    atrText: "Comprendre l'atrophie. L'écart compare à quel point on juge l'IA supérieure à soi (signal de délégation) à ses propres compétences. Un écart positif signale qu'on se repose sur l'IA plus vite qu'on n'entretient ses compétences — un muscle qu'on n'utilise plus finit par s'affaiblir (dynamique du « report du fardeau », Senge). Les trois niveaux :",
    atrLevels: [
      "Sain (≤ 0) — vous entretenez vos compétences au moins autant que vous vous appuyez sur l'IA.",
      "Vigilance (1 à 7) — vous commencez à vous appuyer sur l'IA un peu plus vite que vous ne renforcez vos compétences — à rééquilibrer.",
      "Atrophie probable (> 7) — vous vous en remettez à l'IA nettement plus que vous n'entretenez vos compétences ; la dépendance risque de s'auto-renforcer."],
    keganTitle: "Le niveau de conscience de l'équipe (Robert Kegan)",
    keganText: "Au-delà des compétences, notre relation à l'IA dépend du « lieu » depuis lequel on regarde le monde — ce que Robert Kegan appelle le développement vertical. Un même usage de l'IA n'a pas le même sens selon le stade d'où on l'aborde. Ce n'est pas une échelle de valeur : chaque stade est une façon cohérente de faire sens, et l'on grandit par élargissement, pas par remplacement.",
    keganDefs: [
      "L'esprit socialisé — je me définis par les attentes de mon environnement (équipe, hiérarchie, norme). Face à l'IA : j'adopte l'usage que le groupe valide, difficile de m'en écarter seul. Force : cohésion. Risque : suivre la norme même quand elle dérive — reddition collective.",
      "L'esprit auteur de soi — j'ai mon propre système de valeurs et mes critères. Face à l'IA : je décide selon mes principes, même à contre-courant du groupe. Force : autonomie de jugement. Risque : rigidité, refus de se laisser challenger.",
      "L'esprit auto-transformateur — je vois les limites de mon propre cadre et je tiens plusieurs regards à la fois. Face à l'IA : je m'en sers pour interroger mes certitudes, je tolère la contradiction. Rare, mais clé pour naviguer l'incertitude de l'IA."],
    visionTitle: "Ce que l'équipe veut devenir face à l'IA",
    visionText: "Mots les plus fréquents dans les réponses à « qui voulez-vous que votre équipe devienne face à l'IA dans un an ? ».",
    whereTitle: "Où se situe chacun aujourd'hui",
    whereText: "Ce n'est pas une étiquette mais une relation à l'IA à l'instant t — mouvante et contextuelle. Chaque position est utile et respectable : elle dit quelque chose de juste sur le rapport de la personne à l'outil. En regard, leur réponse à la question de vision.",
    openTitle: "Ce qui ressort des réponses ouvertes",
    openText: "Quelques extraits des réflexions personnelles (les 5 compétences) :",
    firstStepTitle: "Le premier pas",
    firstStepText: "Réponses à « le plus petit essai que l'équipe pourrait lancer cette semaine pour muscler ce qui s'atrophie ? »",
    framesTitle: "Les cadres qui fondent ce diagnostic",
    framesText: "Ce miroir s'appuie sur quatre lectures complémentaires de ce qui se joue, en profondeur, quand l'IA entre dans une équipe :",
    frames: [
      "Robert Kegan — développement vertical — le rapport à l'IA dépend du « lieu » depuis lequel on fait sens : le même outil renforce un esprit auteur de soi et fragilise un esprit socialisé. On grandit en élargissant son cadre, pas en changeant d'outil.",
      "Peter Senge — pensée systémique — la sur-dépendance est un « report du fardeau » : l'IA soulage le symptôme et endort la capacité de fond. Nommer ses modèles mentaux sur l'IA est le premier levier de l'organisation apprenante.",
      "Arnold Mindell — rang & démocratie profonde — qui ose contredire l'IA dépend du rang perçu dans l'équipe. Les voix les plus utiles sont souvent les plus silencieuses ; les faire exister change la décision.",
      "HSD — Human Systems Dynamics (G. Eoyang) — une équipe se régule par trois conditions — Contenant, Différence, Échange. L'action adaptative (Quoi ? Et alors ? Et maintenant ?) transforme ce diagnostic en pas concrets."],
    conclTitle: "En conclusion",
    concl: "Ce rapport n'a qu'un but : ouvrir une conversation. L'IA est entrée dans l'équipe comme un nouveau collègue — puissant, rapide, parfois envahissant. La vraie question n'est pas « faut-il l'utiliser ? » mais « quelle place lui donne-t-on, ensemble et en conscience ? ». Ces chiffres ne tranchent rien : ils offrent un langage commun pour en parler sans se juger, voir où chacun se situe, et décider en équipe du type d'alliance que l'on veut nouer avec l'IA. Le diagnostic n'est que le point de départ — l'alchimie se joue dans la discussion qui suit.",
    keganNames: ['socialisé', 'auteur de soi', 'auto-transformateur'],
    reportTitle: "Rapport d'équipe All(IA)nce",
  },
  en: {
    subtitle: "Cognitive surrender diagnostic",
    intro: "This report is a snapshot, at a point in time, of the kind of relationship your team has with AI — individually and collectively. It is neither an assessment nor a judgment, but a mirror: becoming aware of what we already do, so we can act and consciously build the alliance we want with AI.",
    kpi: { resp: 'Respondents', red: 'Surrender', res: 'Resistance', pol: 'Polarity' },
    howToReadTitle: "How to read the scores",
    howToRead: [
      "Surrender (out of 25) — 5 to 11: healthy delegation · 12 to 18: tipping point · 19 to 25: cognitive surrender. The higher the score, the more AI is adopted without re-examining it.",
      "Resistance (out of 20) — 4 to 9: openness · 10 to 14: moderate refusal · 15 to 20: rigid refusal. The higher the score, the more AI is kept at arm's length."],
    polTitle: "The surrender – resistance polarity",
    polText: "The cursor places the team between surrender (letting AI carry you) and resistance (keeping it at arm's length). Neither pole is a goal or a flaw: they are two complementary tendencies, to be integrated according to context and in the right measure. The point is not to pick a side, but to know how to balance.",
    mapTitle: "The surrender – resistance map",
    mapText: "Each dot is a person; the diamond, the team average. The two axes trace four postures — in the centre, a transition zone, a relationship still settling:",
    postures: {
      over: "Cognitive surrender — we follow AI without re-examining it; judgment is delegated without noticing.",
      rigid: "Rigid refusal — we keep AI at arm's length, sometimes at the cost of our workload and learning.",
      healthy: "Healthy integration — we use it with discernment, neither over-trusting nor rejecting it: the target zone.",
      erratic: "Oscillating judgment — we alternate between blind trust and rejection on principle; the ground rules are still to be set." },
    compTitle: "The 5 human competencies",
    compText: "Creativity, curiosity, collaboration, critical thinking, communication: these are, still today, the most typically human competencies — the ones AI imitates least well and over-dependence erodes fastest. Measuring them shows where humans keep (or lose) their added value. Gold line: the competency you recognise in yourself. Copper line: how far you judge AI superior to you.",
    compP21: "These five competencies form the core of the 21st-century skills (P21 framework). In short:",
    compRefs: [
      "Creativity — producing ideas that are both novel and useful — what AI recombines but does not truly initiate. (Amabile, 1996)",
      "Curiosity — the desire to explore and dig beyond the strictly necessary — the engine of learning. (Kashdan & Silvia, 2009)",
      "Collaboration — tapping the group's collective intelligence, greater than the sum of individuals. (Woolley et al., Science, 2010)",
      "Critical thinking — evaluating a claim, its sources and its biases before accepting it. (Facione, APA Delphi report, 1990)",
      "Communication — adapting your message to be genuinely understood by different audiences. (Hymes, 1972)"],
    compLegend: { cap: 'Your competency', sig: 'AI seen higher' },
    hsdTitle: "The team's dynamics facing AI",
    hsdText: "A team is a system. Three conditions determine its ability to metabolise the arrival of AI rather than endure it. A system that poorly regulates one of the three tips faster into shared surrender.",
    hsdDefs: [
      "Container — the frame, the roles, the ground rules: who decides what about AI.",
      "Difference — the room left for disagreement, divergence, ethics: daring to challenge AI.",
      "Exchange — the flow of information, the debrief, collective learning from mistakes."],
    atrTitle: "Average atrophy gap",
    atrText: "Understanding atrophy. The gap compares how far you judge AI superior to yourself (delegation signal) with your own competencies. A positive gap signals you lean on AI faster than you maintain your competencies — a muscle you stop using eventually weakens (the 'shifting the burden' dynamic, Senge). The three levels:",
    atrLevels: [
      "Healthy (≤ 0) — you maintain your competencies at least as much as you lean on AI.",
      "Watch (1 to 7) — you are starting to lean on AI a little faster than you strengthen your competencies — worth rebalancing.",
      "Likely atrophy (> 7) — you rely on AI markedly more than you maintain your competencies; dependence may become self-reinforcing."],
    keganTitle: "The team's level of consciousness (Robert Kegan)",
    keganText: "Beyond competencies, our relationship with AI depends on the 'place' from which we see the world — what Robert Kegan calls vertical development. The same AI use does not mean the same thing depending on the stage from which we approach it. This is not a value scale: each stage is a coherent way of making meaning, and we grow by broadening, not by replacing.",
    keganDefs: [
      "The socialized mind — I define myself by the expectations of my environment (team, hierarchy, norm). Facing AI: I adopt the use the group validates, hard to deviate alone. Strength: cohesion. Risk: following the norm even when it drifts — collective surrender.",
      "The self-authoring mind — I have my own value system and criteria. Facing AI: I decide by my principles, even against the group. Strength: autonomy of judgment. Risk: rigidity, refusing to be challenged.",
      "The self-transforming mind — I see the limits of my own frame and hold several views at once. Facing AI: I use it to question my own certainties, I tolerate contradiction. Rare, but key to navigating AI's uncertainty."],
    visionTitle: "What the team wants to become facing AI",
    visionText: "Most frequent words in answers to 'who do you want your team to become facing AI in a year?'.",
    whereTitle: "Where each person stands today",
    whereText: "This is not a label but a relationship with AI at a point in time — shifting and contextual. Every position is useful and respectable: it says something true about the person's relationship with the tool. Alongside, their answer to the vision question.",
    openTitle: "What emerges from the open answers",
    openText: "A few excerpts from personal reflections (the 5 competencies):",
    firstStepTitle: "The first step",
    firstStepText: "Answers to 'the smallest experiment the team could launch this week to strengthen what is atrophying?'",
    framesTitle: "The frameworks behind this diagnostic",
    framesText: "This mirror draws on four complementary readings of what is at stake, deep down, when AI enters a team:",
    frames: [
      "Robert Kegan — vertical development — one's relationship with AI depends on the 'place' from which one makes meaning: the same tool strengthens a self-authoring mind and weakens a socialized one. We grow by broadening our frame, not by changing tools.",
      "Peter Senge — systems thinking — over-dependence is a 'shifting the burden': AI eases the symptom and lulls the underlying capacity. Naming your mental models about AI is the first lever of the learning organization.",
      "Arnold Mindell — rank & deep democracy — who dares contradict AI depends on perceived rank in the team. The most useful voices are often the most silent; giving them room changes the decision.",
      "HSD — Human Systems Dynamics (G. Eoyang) — a team self-regulates through three conditions — Container, Difference, Exchange. Adaptive Action (What? So what? Now what?) turns this diagnostic into concrete steps."],
    conclTitle: "In conclusion",
    concl: "This report has a single aim: to open a conversation. AI has entered the team like a new colleague — powerful, fast, sometimes intrusive. The real question is not 'should we use it?' but 'what place do we give it, together and consciously?'. These numbers settle nothing: they offer a shared language to talk about it without judging, to see where each person stands, and to decide as a team the kind of alliance we want to build with AI. The diagnostic is only the starting point — the alchemy happens in the discussion that follows.",
    keganNames: ['socialized', 'self-authoring', 'self-transforming'],
    reportTitle: "All(IA)nce team report",
  },
} as const;
